name: Deploy Jellyfin Intro Auto Skipper

on:   
  push:
    branches:
      - master
    paths:
      - 'jellyfin_auto_skip.py'
      - 'Dockerfile_Jellyfin-Intro-Skipper'

env:
  IMAGE_NAME_SKIPPER: jellyfin-intro-skipper
  REGISTRY: ghcr.io

jobs:
  Skipper_Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Convert Names to Lowercase
        run: |
          echo LOWERCASE_REPOSITORY_OWNER_NAME=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_SKIPPER }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.LOWERCASE_REPOSITORY_OWNER_NAME }}/${{ env.IMAGE_NAME_SKIPPER }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile_Jellyfin-Intro-Skipper